### ISSUE TITLE
actions.invoke returning a 405 (method POST not supported)

### ISSUE THREAD

**Issue by FintanMcElroy** [openwhisk/openwhisk-client-js#12]
I was getting errors trying actions.invoke but not getting any error stack back (using .then().catch(err)). actions.list works fine which means my base setup of API key etc was fine. I added a line of instrumentation into base_operation.js handle_errors() which showed that OW was returning a 405 method not allowed.
![ow_error](https://cloud.githubusercontent.com/assets/23357173/20209852/6ab10330-a7ee-11e6-963c-b5205f28aefd.jpg)

**Comment by jthomas** [comment]
Hello Fintan, 

Can you do a few things to help me diagnose this... 

- Are you able to provide me the output from the following command?

```
wsk action get ACTION_NAME
```

**Ensure you redact any confidential information!**

- Could you provide me the source code for the client library invocation?

- It looks like you are on Windows, what version are you using?

**Comment by jthomas** [comment]
We took this offline to resolve.
