### ISSUE TITLE
Add debugging flags

### ISSUE THREAD

**Issue by jthomas** [openwhisk/openwhisk-client-js#15]
Use environment variable to turn on help debugging by dumping more information about API requests to the console.

**Comment by jthomas** [comment]
I've been looking into surfacing HTTP traces to assist debugging issues. This library uses the request npm module as the HTTP client. I've discovered this library supports a configuration flag to dump HTTP traffic.

```
NODE_DEBUG=request node script.js
```

Here's an example of the output for the following code.
```
var ow = openwhisk({api_key: 'xxx:yyy', apihost: 'openwhisk.ng.bluemix.net', namespace: 'james.thomas@uk.ibm.com_dev'});

ow.actions.list().then(console.log).catch(console.log)
```

```
NODE_DEBUG=request node test.js
REQUEST { json: true,
  method: 'GET',
  url: 'https://openwhisk.ng.bluemix.net/api/v1/namespaces/james.thomas%40uk.ibm.com_dev/actions',
  rejectUnauthorized: true,
  headers: { Authorization: 'Basic xxxxxx=' },
  qs: {},
  callback: undefined,
  transform: undefined,
  simple: true,
  resolveWithFullResponse: false }
REQUEST make request https://openwhisk.ng.bluemix.net/api/v1/namespaces/james.thomas%40uk.ibm.com_dev/actions
REQUEST onRequestResponse https://openwhisk.ng.bluemix.net/api/v1/namespaces/james.thomas%40uk.ibm.com_dev/actions 200 { 'x-backside-transport': 'OK OK',
  connection: 'close',
  'transfer-encoding': 'chunked',
  server: 'nginx/1.11.10',
  date: 'Sat, 11 Mar 2017 08:48:07 GMT',
  'content-type': 'application/json; charset=UTF-8',
  'access-control-allow-origin': '*',
  'access-control-allow-headers': 'Authorization, Content-Type',
  'x-global-transaction-id': '3848629955',
  'set-cookie': [ 'DPJSESSIONID=xxxx; Path=/; Domain=.whisk.ng.bluemix.net' ] }
REQUEST reading response's body
REQUEST finish init function https://openwhisk.ng.bluemix.net/api/v1/namespaces/james.thomas%40uk.ibm.com_dev/actions
REQUEST response end https://openwhisk.ng.bluemix.net/api/v1/namespaces/james.thomas%40uk.ibm.com_dev/actions 200 { 'x-backside-transport': 'OK OK',
  connection: 'close',
  'transfer-encoding': 'chunked',
  server: 'nginx/1.11.10',
  date: 'Sat, 11 Mar 2017 08:48:07 GMT',
  'content-type': 'application/json; charset=UTF-8',
  'access-control-allow-origin': '*',
  'access-control-allow-headers': 'Authorization, Content-Type',
  'x-global-transaction-id': '3848629955',
  'set-cookie': [ 'DPJSESSIONID=xxxx; Path=/; Domain=.whisk.ng.bluemix.net' ] }
REQUEST end event https://openwhisk.ng.bluemix.net/api/v1/namespaces/james.thomas%40uk.ibm.com_dev/actions
REQUEST has body https://openwhisk.ng.bluemix.net/api/v1/namespaces/james.thomas%40uk.ibm.com_dev/actions 945
REQUEST emitting complete https://openwhisk.ng.bluemix.net/api/v1/namespaces/james.thomas%40uk.ibm.com_dev/actions
```

This looks like a good solution for helping to get HTTP traffic when encountering issues. 
@rabbah & @starpit - what do you think? is this enough? 

If we like this, I'll document it in the README.md as our solution.

**Comment by starpit** [comment]
For me, the main thing is being specific about failures. The cli has the same problem (and itself had open issues on this very point).

Right now, I neither get specifics a out my failing request, nor (and worse, in my opinion) a helpful stack trace. The stack trace is blinded by some async intermediary. 

With the proposal, I would... Have to return my failing request? This won't help with prod failures. And, anyway, how does one inject an envvar in to a whisk-excuted action?

**Comment by jthomas** [comment]
I've added information about this feature to the README.
https://github.com/openwhisk/openwhisk-client-js/blob/master/README.md#debugging

Turning this on at runtime can be done like....
```
process.env.NODE_DEBUG='request';
var openwhisk = require('openwhisk');

function main(params) {
  var ow = openwhisk();  

  return ow.actions.list().then(arr => ({result: arr}))
}
```

**Comment by jthomas** [comment]
@starpit I agree that the error responses from the library could be more helpful but I think some of that is due to that platform responses. 

I'm going to close this ticket as resolved and can we open another issue for error messages and discuss requirements?
