### ISSUE TITLE
Actions test uses payload instead of params when sending JSON string

### ISSUE THREAD

**Issue by ErikWittern** [openwhisk/openwhisk-client-js#19]
In the test for invoking an action using a JSON string (`actions.test.js`, line 413 ff) the JSON string is defined in a `payload` field, rather than in the `params` field. Furthermore, it is an empty object, which is equal to the default when no params are provided - so the test will always succeed.

**Comment by jthomas** [comment]
Hey @ErikWittern, thanks for reporting this! 

I'll look into it and get a fix in this week.

**Comment by jthomas** [comment]
Looking into this, the test is verifying a feature that doesn't exist in the implementation. 
I've removed the test, thanks for letting me know.
