### ISSUE TITLE
support default parameters for actions

### ISSUE THREAD

**Issue by ddragosd** [openwhisk/openwhisk-client-js#25]
When creating an action it would be great to be able to provide default parameters.

**Comment by jthomas** [comment]
https://github.com/openwhisk/openwhisk-client-js/pull/26 @ddragosd is working on this.

**Comment by jthomas** [comment]
@ddragosd I've done a lot of re-factoring so I've merged your code into the current code base. This is now supported. Thanks for the suggestion!

**Comment by ddragosd** [comment]
Thanks a lot @jthomas. I didn't have the time to finish the integration tests so it's super you were able to integrate it with the refactoring.
