### ISSUE TITLE
feature request: support "name" for get, invoke operations

### ISSUE THREAD

**Issue by starpit** [openwhisk/openwhisk-client-js#28]
right now, i find that my code is littered with things like:
```
Promise.all(triggers.map(trigger => ow.triggers.invoke({ triggerName: trigger.name })))
```

it seems preferable to me to write:
```
Promise.all(triggers.map(ow.triggers.invoke))
```

but i can't, because the `get` and `invoke` operations require `triggerName`, or `actionName` or `packageName` or `ruleName` rather than just `name`.

on top of this, having an `invokeAll` or `getAll` command would be nice, so that i could write
```
ow.packages.get('foo').then(package=>package.actions).then(ow.actions.getAll)
```

and having a simple projection mechanism would then simplify this to:

```
ow.packages.getActions('foo').then(ow.actions.getAll)
```

compare this to what we have now:

```
ow.packages.get('foo').then(package=>package.actions)
    .then(Promise.all(triggers.map(trigger=>ow.triggers.invoke({triggerName:trigger.name})))
```

**Comment by jthomas** [comment]
This is a good idea. I would need to bump the version number as this would be a breaking change. 

We should probably review the API to see what other usability changes we can include if we're going to push out a major version upgrade.

**Comment by rabbah** [comment]
support both for backward compatibility?

**Comment by starpit** [comment]
as long as we prefer `xName` to `name`... this should be sufficient, in terms of backwards compatibility? the only cases i can think of are those that, before, would in an error, that now will not: `ow.actions.create({name: 'foo'}) would before result in an error, and now succeed... 

perhaps that is ok?

**Comment by rabbah** [comment]
+1 that's better than breaking all the existing actions. since we just forced everyone to get off whisk.js would be nice not to make another forced change.

**Comment by starpit** [comment]
i just added a **projection** suggestion to the initial feature request comment (i.e. at the top)

**Comment by jthomas** [comment]
### Supporting Different Parameters

I'm going to support the resource identifiers returned by the platform API to chaining promises together. This will be `name` in most examples but there are additional edge cases like `activationId`. 

I will maintain support for the existing parameter names for backwards capability. 

### Support String Parameters

I also might support passing in the identifier as a string, in addition to the object, to simplify simple invocations. 

```
ow.actions.invoke('actionName')
```

**Any objections?** 

### Chaining Promises

Looking at the example above about chaining promises, it will encounter an issue that the API uses inheritance to share a base class and needs the lexical context bound to the invocation. Arrow functions will be needed to resolve this without resorting to `function.bind`
```
Promise.all(triggers.map(trigger => ow.triggers.invoke(trigger)))
```

I don't like the style of having a separate method for interacting with multiple resources. It feels cluttered to me. 

I suggest supporting array parameters for the relevant resource methods, as shown here: 

```
ow.actions.list()
  .then(actions => ow.actions.invoke(actions))
  .then(result => ...)
```

That seems to be a relatively clean way to support interacting with multiple resources without having to remember different API calls. 

**Thoughts? @starpit  @rabbah**

**Comment by starpit** [comment]
this all seems reasonable. thanks!

**Comment by jthomas** [comment]
I've been refactoring the library to make supporting these features easier. `id` is now supported along with the old style. 

Remaining items. 

- [ ] update docs with new features
- [ ] support string identifiers
- [ ] support array of identifiers

**Comment by jthomas** [comment]
This is now ready with v3.3.0.
