### ISSUE TITLE
Feature request: Result only flag for action invoke

### ISSUE THREAD

**Issue by ioana-blue** [openwhisk/openwhisk-client-js#29]
Is there an option similar to the `-r` in the `wsk` cli that returns only the result of the invocation (used together with `-b` or `blocking = true`)? I'd use it all the time :)

On a related note, I don't think I understand how this example in the readme works:

```const actionName = 'reverseWords'
const blocking = true
const params = {msg: 'this is some words to reverse'}

ow.actions.invoke({actionName, blocking, params}).then(result => {
  console.log('here's the reversed string', result.reversed)
}).catch(err => {
  console.error(failed to invoke actions', err)
})
```
IIUC the result of the invocation will contain not only the "result", but all the other meta data (e.g., duration, name, annotations, etc.) and I would expect `result.reversed` to be undefined. New to js, what am I missing?

**Comment by tareqmamari** [comment]
result object contains the whole response (of the invocation request) from OpenWhisk. Now, to access the result of the execution, you can directly access it from the nested-object "response". In other words, you can get the result of the action execution as:

```
ow.actions.invoke({
	actionName,
	blocking,
	params
}).then(invokationResponse => console.log(invokationResponse.response.result))
.catch(error => console.error(error));
```
So, from your example, to access the reversed string: `result.response.reversed `.

I hope this can help.

**Comment by ioana-blue** [comment]
@tareqmamari Thanks for confirming my understanding. Note that the example above it's not "my" example, it's the example in the documentation of the client here:

https://github.com/openwhisk/openwhisk-client-js#invoke-action-blocking-for-result

which I thought it was wrong (and you confirmed, thanks!)

**Comment by tareqmamari** [comment]
yes exactly, maybe it will be a good idea to mention that in the docs.

**Comment by jthomas** [comment]
@ioana-blue This should be easy to implement. I'll add it to the list of things to do :)
