### ISSUE TITLE
action.get does not return parameters bound to an action

### ISSUE THREAD

**Issue by kerryspchang** [openwhisk/openwhisk-client-js#33]
Whisk's CLI returns parameters bound to an action when using "wsk action get" (in an array called "parameters" that has objects storing each parameter's name and value). 

But the parameter information is gone in the nodeJS library when using actions.get - the parameters array is always empty (or only has an "_actions" object for a sequence action).

**Comment by jthomas** [comment]
Thanks for reporting this. I'll look into it.

**Comment by kerryspchang** [comment]
Have you had time to look into this?

**Comment by jthomas** [comment]
I have not. I'll update the ticket when I investigate. This is not high on my priorities list at the moment. 

If you want to investigate and submit a PR, I'll happily merge.

**Comment by jthomas** [comment]
Hello @kerryspchang, I've tested with with a sample action and can see the default parameters coming back.

```
> ow.actions.get('webhook').then(console.log)
{ name: 'webhook',
  publish: false,
  annotations: [],
  version: '0.0.1',
  exec:
   { kind: 'nodejs:6',
     code: '...',
     binary: false },
  parameters:
   [ { key: 'url',
       value: '...' },
     { key: 'channel', value: '#weather' },
     { key: 'username', value: 'Weather Bot' },
     { key: 'icon_emoji', value: ':sun_with_face:' } ],
  limits: { timeout: 60000, memory: 256, logs: 10 },
  namespace: 'james.thomas@uk.ibm.com_dev' }
```
Can you provide a test case?

**Comment by jthomas** [comment]
Is this issue still happening? If so, do you have test data I can check?
