### ISSUE TITLE
Add support for error response coming out of OpenWhisk action invocation

### ISSUE THREAD

**Issue by lionelvillard** [openwhisk/openwhisk-client-js#40]
action being invoked:

    function main(args) {
        return new Promise((resolve, reject) => { reject({ statusCode: 404 }) };
    }

The invocation of this action through the REST API produces this response:
    
   {
     "error": {
         "statusCode": 404
     }
   }

However OpenWhisk Client expect the statusCode to be at the top-level, and I think we should change this behavior to also support OpenWhisk error response.

**Comment by jthomas** [comment]
Thanks for the suggestion. I need to review the error reporting to make it more robust and will look at this.

**Comment by jthomas** [comment]
I've added support into the error handling code for this.
