### ISSUE TITLE
Are multiple openwhisk() objects supported ?

### ISSUE THREAD

**Issue by pjdurai** [openwhisk/openwhisk-client-js#42]
Greetings

I am looking into the JS api and have a question.

var options = {apihost: 'openwhisk.ng.bluemix.net', api_key: '...'};
var ow = openwhisk(options);

Is it possible to have multiple 'ow' objects , with different API key/Namespace combos in the same Node.js application? 

Does the library have any global/singleton properties that preclude that kind of usage?

Thanks
pj

**Comment by csantanapr** [comment]
yes every `openwhisk(options);` it's a `new` instance
https://github.com/openwhisk/openwhisk-client-js/blob/master/lib/main.js#L12
