### ISSUE TITLE
Many Action Invocations: EPIPE / PROTOCOL_CONNECTION_LOST

### ISSUE THREAD

**Issue by jlost** [openwhisk/openwhisk-client-js#48]
Hi, I'm invoking many actions from inside a parent action over a long (3-5 mins) period of time. We're running against an on-premises OpenWhisk cluster. The code invoking the actions is along the lines of:

```
const invokeAction = (openwhisk, v) => {
    return openwhisk.actions.invoke({
        name: "my-action",
        params: { param: "val" },
        insecure: true,
        blocking: true  //different error depending on whether true or false
    });
};
const ow = openwhisk({ ignore_certs: true });
rxObservableEmittingMySqlData
    .bufferCount(1000) //buffer to accomodate 1MB max message size
    .zip(Observable.timer(0, 800) x => x) //this will add a .8s delay before each action invocation - without this, I get "too many actions for namespace"
    .flatMap(v => Observable.fromPromise(invokeAction(ow, v)), 30)  //where 30 is maximum concurrent in-flight requests - these problems occur regardless of this value
    .subscribe(console.log, reject, resolve);
```

Error If blocking = true:
```
"response": {
        "status": "application error",
        "statusCode": 0,
        "success": false,
        "result": {
            "error": {
                "error": {
                    "code": "EPIPE",
                    "errno": "EPIPE",
                    "syscall": "write"
                },
                "message": "Unknown Error From API: Error: write EPIPE",
                "name": "OpenWhiskError"
            }
        }
    }
```

Error If blocking = false:
```
{"fatal":true, "code": "PROTOCOL_CONNECTION_LOST"}
```

Even though more OW instances were added to our cluster, it also doesn't seem like the actions aren't completing quickly enough (even when I remove/reduce my throttling), and even if not for these errors I'd be hitting the 5 minute timeout.

Is this the wrong approach for handling millions of MySQL records with OpenWhisk? Is OW even the right tool for the job?

**Comment by jthomas** [comment]
Thanks for the detailed error report. It looks like the issue might be with the openwhisk platform rather than the client library. 

@rabbah @markusthoemmes @jasonpet - have you encountered this error before? 

I think it might make sense to move this ticket over to the core project.

**Comment by rabbah** [comment]
Did you rule out the sql server being down? The error suggests the action is failing to either connect or hold the connection to the sql server. 

I don't understand how the non blocking invoke is change the behavior in the way you describe, yet. I assume you are _returning_ the promise from your main function (and the code snippet above just doesn't show that).

**Comment by rabbah** [comment]
btw since you are running in your own cluster, you can elect to bump the activation throttles (the default is 60 per minute but that too low if you have a cluster with many invokers).

**Comment by jlost** [comment]
Thanks all, I think this particular problem might have been caused by not having proper backpressure on the MySQL server. When I added a pause after "bufferCount" and an unpause on "subscribe", I was able to move past the EPIPE error. My best guess is that the Node.JS process had an out of memory error, and it wasn't handled particularly gracefully by OW, resulting in the EPIPE error. 

However, I do now get a different error: 
```
        "2017-04-20T13:43:39.305332731Z stderr: {\"name\":\"OpenWhiskError\",\"message\":\"POST https://10.255.33.10/api/v1/namespaces/whisk.system/actions/hash-and-load Returned HTTP 502 (Bad Gateway) --\u003e \\\"Response Missing Error Message.\\\"\",\"error\":\"\u003chtml\u003e\\r\\n\u003chead\u003e\u003ctitle\u003e502 Bad Gateway\u003c/title\u003e\u003c/head\u003e\\r\\n\u003cbody bgcolor=\\\"white\\\"\u003e\\r\\n\u003ccenter\u003e\u003ch1\u003e502 Bad Gateway\u003c/h1\u003e\u003c/center\u003e\\r\\n\u003chr\u003e\u003ccenter\u003enginx/1.11.13\u003c/center\u003e\\r\\n\u003c/body\u003e\\r\\n\u003c/html\u003e\\r\\n\"}",
        "2017-04-20T13:43:39.308582823Z stderr: (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): OpenWhiskError: POST https://10.255.33.10/api/v1/namespaces/whisk.system/actions/hash-and-load Returned HTTP 502 (Bad Gateway) --\u003e \"Response Missing Error Message.\""
```

I think this one is pretty clearly not related to the OW JS client, though.
