### ISSUE TITLE
support specifying kind of action

### ISSUE THREAD

**Issue by aslom** [openwhisk/openwhisk-client-js#9]
currently nodejs is hardcoded

```
    return { exec: { kind: 'nodejs', code: options.action } }
```

https://github.com/openwhisk/openwhisk-client-js/blob/master/lib/actions.js#L79

**Comment by jthomas** [comment]
This behaviour is actually already supported. 
https://github.com/openwhisk/openwhisk-client-js/blob/master/lib/actions.js#L75

If the user passes the `options.action` parameter as an object, the entire property is copied over. 
Users can use this to set up the kind property manually.
